### PR TITLE
Add GitHub Actions workflow

### PR DESCRIPTION
**Pull request by bershanskiy**
This actually creates a CI workflow which will be triggered by future pushes and PRs. Also, you can run this workflow on existing PRs created by Dependabot by merging this PR and then asking Dependabot to rebase its PRs.

If you have any questions about GitHub Actions, how they are triggered, and billing, I can answer your questions.

### CODE REVIEW

**Comment by bershanskiy** [comment]
[Here is an example run of this workflow](https://github.com/bershanskiy/svelte-devtools/runs/2721279853). (Workflows do not run in the context of a project when they are modified in PR by a user who does not have write permission to the said project.)

**Comment by RedHatter** [comment]
Don't know how useful this would be as we don't have any tests.

**Comment by bershanskiy** [comment]
I want to add a linter and some E2E tests at some point. Is it OK to add Puppeteer and Mocha, and ESLint as dev dependencies?
Right now, though, this CI workflow won't do anything useful besides just making sure Dependabot's PRs actually still build.

**Comment by RedHatter** [comment]
Tests are a... complex issue. When I originally looked into writing automated tests I found that since Svelte DevTools is an addon running in a chrome DevTools panel that there wasn't any good way to write tests. I'm working on extracting most of the core of the addon into a separate package. Once that's finished then it should be much easier to test.

Also of note: personally I greatly dislike mocha for testing.

I would prefer to hold off on adding any CI until it does something useful. I'm closing this for now.

**Pull request closed without merging**
